version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  
  settings:
    govet:
      enable-all: true
    errcheck:
      check-blank: true 
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

  enable:
    - govet        # Стандартные проверки компилятора
    - errcheck     # Проверка необработанных ошибок
    - staticcheck  # Набор проверок на баги и производительность
    - gosimple     # Упрощение избыточного кода
    - unused       # Поиск неиспользуемого кода
    - ineffassign  # Поиск неэффективных присваиваний
    - gocritic     # Проверки стилистики и микро-оптимизаций
    - gosec        # Поиск уязвимостей

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
