run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    enable-all: true
  errcheck:
    check-blank: true # Проверяет, чтобы ошибки не игнорировались через `_`
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

linters:
  disable-all: true
  enable:
    - govet        # Стандартные проверки компилятора (printf, копирование локов)
    - errcheck     # Проверка необработанных ошибок
    - staticcheck  # Огромный набор проверок на баги и производительность
    - gosimple     # Упрощение избыточного кода
    - unused       # Поиск неиспользуемого кода (переменные, функции, структуры)
    - ineffassign  # Поиск неэффективных присваиваний
    - typecheck    # Проверка типов данных
    - gocritic     # Проверки стилистики и микро-оптимизаций
    - gosec        # Поиск уязвимостей (hardcoded пароли, слабые шифры)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
