version: '3.8'

services:
  api-gateway:
    image: golang:1.25-alpine
    container_name: gateway-dev
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - CLUSTER_DOMAIN=               # Для Docker Compose домен не нужен
    command: go run cmd/gateway/main.go
    depends_on:
      - mock-service
    networks:
      - notion-network

  # Заглушка микросервиса для проверки маршрутизации
  # Гейтвей по пути /api/v1/mock-service/... перенаправит запрос сюда
  mock-service:
    image: hashicorp/http-echo:1.0.0
    container_name: mock-service
    # Передаем текст ответа и порт, который должен слушать контейнер
    command: -text="Hello from Mock Service!" -listen=:8080
    ports:
      - "8081:8080" # Доступен локально на 8081, а в сети compose как http://mock-service:8080
    networks:
      - notion-network

networks:
  notion-network:
    driver: bridge
