// Code generated by registrygen. DO NOT EDIT.
package registry

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	marketingv1 "github.com/notion-clone-app/protos/gen/go/proto/marketing"
	ssov1 "github.com/notion-clone-app/protos/gen/go/proto/sso"
	"google.golang.org/grpc"
)

// Service describes a public HTTP-to-gRPC route.
type Service struct {
	Name         string
	Upstream     string
	GRPCService  string
	AuthRequired bool
	Register     RegisterFunc
}

// RegisterFunc is the signature generated by grpc-gateway.
type RegisterFunc func(
	context.Context,
	*runtime.ServeMux,
	string,
	[]grpc.DialOption,
) error

// PublicHTTPServices returns explicitly allowed HTTP services.
func PublicHTTPServices() []Service {
	return []Service{
		{
			Name:         "auth",
			Upstream:     "sso",
			GRPCService:  "auth.Auth",
			AuthRequired: false,
			Register:     ssov1.RegisterAuthHandlerFromEndpoint,
		},
		{
			Name:         "marketing",
			Upstream:     "marketing",
			GRPCService:  "marketing.Marketing",
			AuthRequired: true,
			Register:     marketingv1.RegisterMarketingHandlerFromEndpoint,
		},
	}
}

// PublicGRPCServices returns the native gRPC service whitelist.
func PublicGRPCServices() []Service {
	return []Service{
		{
			Name:         "auth",
			Upstream:     "sso",
			GRPCService:  "auth.Auth",
			AuthRequired: false,
		},
		{
			Name:         "marketing",
			Upstream:     "marketing",
			GRPCService:  "marketing.Marketing",
			AuthRequired: true,
		},
	}
}

// AuthRequired reports whether a full gRPC method requires authentication.
func AuthRequired(fullMethod string) bool {
	for _, service := range PublicHTTPServices() {
		prefix := "/" + service.GRPCService + "/"
		if len(fullMethod) > len(prefix) && fullMethod[:len(prefix)] == prefix {
			return service.AuthRequired
		}
	}
	return false
}
