package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"text/template"

	"gopkg.in/yaml.v3"
)

type Catalog struct {
	Version  int       `yaml:"version"`
	Services []Service `yaml:"services"`
}

type Service struct {
	Name        string   `yaml:"name"`
	Upstream    string   `yaml:"upstream"`
	GRPCService string   `yaml:"grpc_service"`
	Auth        string   `yaml:"auth"`
	Go          GoConfig `yaml:"go"`
	Exposure    Exposure `yaml:"exposure"`
	Owner       string   `yaml:"owner"`
}

type GoConfig struct {
	Import   string `yaml:"import"`
	Alias    string `yaml:"alias"`
	Register string `yaml:"register"`
}

type Exposure struct {
	HTTP bool `yaml:"http"`
	GRPC bool `yaml:"grpc"`
}

type TemplateData struct {
	HTTPServices []Service
	GRPCServices []Service
}

var identifierPattern = regexp.MustCompile(
	`^[A-Za-z_][A-Za-z0-9_]*$`,
)

func main() {
	var configPath string
	var outputPath string

	flag.StringVar(
		&configPath,
		"config",
		"",
		"path to services catalog",
	)
	flag.StringVar(
		&outputPath,
		"out",
		"",
		"path to generated Go file",
	)
	flag.Parse()

	if configPath == "" {
		exitf("-config is required")
	}
	if outputPath == "" {
		exitf("-out is required")
	}

	catalog, err := loadCatalog(configPath)
	if err != nil {
		exitf("load catalog: %v", err)
	}

	if err := validateCatalog(catalog); err != nil {
		exitf("validate catalog: %v", err)
	}

	sort.Slice(catalog.Services, func(i, j int) bool {
		return catalog.Services[i].Name < catalog.Services[j].Name
	})

	publicHTTP := make([]Service, 0, len(catalog.Services))
	publicGRPC := make([]Service, 0, len(catalog.Services))
	for _, service := range catalog.Services {
		if service.Exposure.HTTP {
			publicHTTP = append(publicHTTP, service)
		}
		if service.Exposure.GRPC {
			publicGRPC = append(publicGRPC, service)
		}
	}

	var generated bytes.Buffer
	err = registryTemplate.Execute(&generated, TemplateData{
		HTTPServices: publicHTTP,
		GRPCServices: publicGRPC,
	})
	if err != nil {
		exitf("execute template: %v", err)
	}

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		exitf("format generated source: %v", err)
	}

	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		exitf("write generated file: %v", err)
	}
}

func loadCatalog(path string) (*Catalog, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var catalog Catalog

	if err := yaml.Unmarshal(data, &catalog); err != nil {
		return nil, err
	}

	return &catalog, nil
}

func validateCatalog(catalog *Catalog) error {
	if catalog.Version != 1 {
		return fmt.Errorf(
			"unsupported catalog version %d",
			catalog.Version,
		)
	}

	names := make(map[string]struct{})
	aliases := make(map[string]struct{})

	for index, service := range catalog.Services {
		prefix := fmt.Sprintf("services[%d]", index)

		if service.Name == "" {
			return fmt.Errorf("%s.name is required", prefix)
		}
		if _, exists := names[service.Name]; exists {
			return fmt.Errorf(
				"duplicate service name %q",
				service.Name,
			)
		}
		names[service.Name] = struct{}{}

		if service.Upstream == "" {
			return fmt.Errorf(
				"%s.upstream is required",
				prefix,
			)
		}
		if service.GRPCService == "" {
			return fmt.Errorf("%s.grpc_service is required", prefix)
		}
		if service.Auth != "public" && service.Auth != "required" {
			return fmt.Errorf("%s.auth must be public or required", prefix)
		}

		if !service.Exposure.HTTP {
			// Go gateway registration для этого сервиса
			// генерировать не потребуется.
			continue
		}

		if service.Go.Import == "" {
			return fmt.Errorf(
				"%s.go.import is required",
				prefix,
			)
		}
		if !identifierPattern.MatchString(service.Go.Alias) {
			return fmt.Errorf(
				"%s.go.alias %q is not a Go identifier",
				prefix,
				service.Go.Alias,
			)
		}
		if !identifierPattern.MatchString(service.Go.Register) {
			return fmt.Errorf(
				"%s.go.register %q is not a Go identifier",
				prefix,
				service.Go.Register,
			)
		}

		if _, exists := aliases[service.Go.Alias]; exists {
			return fmt.Errorf(
				"duplicate Go alias %q",
				service.Go.Alias,
			)
		}
		aliases[service.Go.Alias] = struct{}{}
	}

	return nil
}

func exitf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

var registryTemplate = template.Must(
	template.New("registry").Parse(`// Code generated by registrygen. DO NOT EDIT.
package registry

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
{{- range .HTTPServices }}
	{{ .Go.Alias }} "{{ .Go.Import }}"
{{- end }}
)

// Service describes a public HTTP-to-gRPC route.
type Service struct {
	Name         string
	Upstream     string
	GRPCService  string
	AuthRequired bool
	Register     RegisterFunc
}

// RegisterFunc is the signature generated by grpc-gateway.
type RegisterFunc func(
	context.Context,
	*runtime.ServeMux,
	string,
	[]grpc.DialOption,
) error

// PublicHTTPServices returns explicitly allowed HTTP services.
func PublicHTTPServices() []Service {
	return []Service{
{{- range .HTTPServices }}
		{
			Name:         "{{ .Name }}",
			Upstream:     "{{ .Upstream }}",
			GRPCService:  "{{ .GRPCService }}",
			AuthRequired: {{ eq .Auth "required" }},
			Register:     {{ .Go.Alias }}.{{ .Go.Register }},
		},
{{- end }}
	}
}

// PublicGRPCServices returns the native gRPC service whitelist.
func PublicGRPCServices() []Service {
	return []Service{
{{- range .GRPCServices }}
		{
			Name:         "{{ .Name }}",
			Upstream:     "{{ .Upstream }}",
			GRPCService:  "{{ .GRPCService }}",
			AuthRequired: {{ eq .Auth "required" }},
		},
{{- end }}
	}
}

// AuthRequired reports whether a full gRPC method requires authentication.
func AuthRequired(fullMethod string) bool {
	for _, service := range PublicHTTPServices() {
		prefix := "/" + service.GRPCService + "/"
		if len(fullMethod) > len(prefix) && fullMethod[:len(prefix)] == prefix {
			return service.AuthRequired
		}
	}
	return false
}
`),
)
